### ISSUE TITLE
 TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (None, 1, 1). Consider casting elements to a supported type.

### ISSUE THREAD

**Issue by big-ai** [rishigami/Swin-Transformer-TF#6]
How to solve this problem? Thank you

**Comment by rishigami** [comment]
I fixed some codes. Could you try again?
(P.S. I couldn't reproduce the problem. Which OS do you use?)

**Comment by big-ai** [comment]
After you modify the code, it can run normally. Thank you very much!

**Comment by big-ai** [comment]
Can you tell me which code you changed? I've lost your previous code

**Comment by rishigami** [comment]
You can check from this [commit](https://github.com/rishigami/Swin-Transformer-TF/commit/8986ca7b0e1f984437db2d8f17e0ecd87fadcd4f).
